set_project("nassistant-duilib-launcher")
set_version("0.1.0")
set_xmakever("2.7.9")

add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "."})
add_requires("nlohmann_json", "gtest")

includes("libicon-core")
includes("libicon-qt")
includes("libant-qt")
includes("libant-qt-demo")
includes("cpp-duilib-launcher")
includes("ant_demo")
includes("qt6_widget_demo")
